"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useI18n} from '../i18n/LanguageContext';
import {getAdvertisementTickerSettings,saveAdvertisementTickerSettings,type AdvertisementTickerSettings,type AdvertisementTickerWrite} from '../services/advertisements';

export function AdvertisementTickerControls(){
 const {t}=useI18n();const [attempt,setAttempt]=useState(0);const [snapshot,setSnapshot]=useState<{attempt:number;settings?:AdvertisementTickerSettings;error?:string}>();
 useEffect(()=>{const controller=new AbortController();getAdvertisementTickerSettings(controller.signal).then(settings=>{if(!controller.signal.aborted)setSnapshot({attempt,settings});}).catch(error=>{if(!controller.signal.aborted)setSnapshot({attempt,error:(error as Error).message});});return()=>controller.abort();},[attempt]);
 const current=snapshot?.attempt===attempt?snapshot:undefined;
 return <details className="ad-desk-card ad-ticker-controls"><summary>{t('Homepage top-bar settings','মূল পাতার ওপরের বিজ্ঞাপনবার নিয়ন্ত্রণ')}</summary><p>{t('Control the entire ticker here. Use each advertisement’s editor to choose its placement and short message.','সম্পূর্ণ বিজ্ঞাপনবার এখান থেকে নিয়ন্ত্রণ করুন। প্রতিটি বিজ্ঞাপনের সম্পাদক থেকে প্রদর্শন ও সংক্ষিপ্ত বার্তা বেছে নিন।')}</p>{!current?<p role="status">{t('Loading settings…','নিয়ন্ত্রণ লোড হচ্ছে…')}</p>:current.error?<div role="alert"><p>{current.error}</p><button type="button" onClick={()=>setAttempt(value=>value+1)}>{t('Retry','আবার চেষ্টা করুন')}</button></div>:current.settings?<TickerEditor key={attempt} settings={current.settings}/>:null}</details>;
}
function TickerEditor({settings}:{settings:AdvertisementTickerSettings}){
 const {t}=useI18n();const [draft,setDraft]=useState<AdvertisementTickerWrite>({...settings,decision_rationale:''});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const pending=useRef(false);const active=useRef(true);
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 async function save(event:FormEvent){event.preventDefault();if(pending.current)return;if(!draft.policy_en.trim()||!draft.policy_bn.trim()||draft.decision_rationale.trim().length<10){setMessage(t('Enter both policy messages and a decision reason of at least 10 characters.','দুই ভাষায় নীতির বার্তা এবং অন্তত ১০ অক্ষরে সিদ্ধান্তের কারণ লিখুন।'));return;}pending.current=true;setBusy(true);setMessage('');try{const result=await saveAdvertisementTickerSettings({...draft,policy_en:draft.policy_en.trim(),policy_bn:draft.policy_bn.trim(),decision_rationale:draft.decision_rationale.trim()});if(active.current){setDraft({...result,decision_rationale:''});setMessage(t('Saved on the server. Refresh the homepage to see the updated ticker.','সার্ভারে সংরক্ষিত হয়েছে। পরিবর্তিত বিজ্ঞাপনবার দেখতে মূল পাতা আবার লোড করুন।'));}}catch(reason){if(active.current)setMessage((reason as Error).message);}finally{pending.current=false;if(active.current)setBusy(false);}}
 return <form onSubmit={save} aria-busy={busy}><fieldset disabled={busy}><label className="ad-desk-checkbox"><input type="checkbox" checked={draft.enabled} onChange={event=>setDraft(value=>({...value,enabled:event.target.checked}))}/>{t('Show advertisement top bar on the homepage','মূল পাতায় ওপরের বিজ্ঞাপনবার দেখান')}</label><div className="ad-desk-columns">{(['en','bn'] as const).map(locale=><label key={locale}>{locale==='en'?'Policy message · English':'নীতির বার্তা · বাংলা'}<textarea rows={3} maxLength={1000} required value={draft[`policy_${locale}`]} onChange={event=>setDraft(value=>({...value,[`policy_${locale}`]:event.target.value}))}/></label>)}</div><label>{t('Private decision reason','ব্যক্তিগত সিদ্ধান্তের কারণ')}<textarea rows={2} required minLength={10} maxLength={2000} value={draft.decision_rationale} onChange={event=>setDraft(value=>({...value,decision_rationale:event.target.value}))}/></label></fieldset>{message&&<p role="status" className="ad-desk-message">{message}</p>}<button type="submit" className="ad-desk-primary" disabled={busy}>{busy?t('Saving…','সংরক্ষণ হচ্ছে…'):t('Save top-bar settings','বিজ্ঞাপনবারের নিয়ন্ত্রণ সংরক্ষণ')}</button></form>;
}
