"use client";
import {useEffect,useId,useState} from 'react';
import {FileText,Images,LockKeyhole,Plus,X} from 'lucide-react';
import {LazyMotion,domAnimation,m,useReducedMotion} from 'motion/react';
import {MAX_ATTACHMENT_TOTAL_MB,selectAttachments} from './attachmentSelection';
import {useI18n} from '../i18n/LanguageContext';
import {formatNumber} from '../i18n/dictionary';

function Attachment({file,onRemove,disabled}:{file:File;onRemove:()=>void;disabled:boolean}){
 const {lang,t}=useI18n();const [preview,setPreview]=useState('');
 useEffect(()=>{if(!file.type.startsWith('image/'))return;const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 return <li className="attachment-tile">{preview?<img src={preview} alt={t('Selected attachment: ','নির্বাচিত ফাইল: ')+file.name}/>:<span className="attachment-document"><FileText size={32} aria-hidden="true"/>{t('PDF document','পিডিএফ নথি')}</span>}<div><strong title={file.name}>{file.name}</strong><small>{formatNumber(file.size/1024/1024,lang,{minimumFractionDigits:2,maximumFractionDigits:2})} {t('MB · Not submitted yet','এমবি · এখনো জমা হয়নি')}</small></div><button type="button" disabled={disabled} onClick={onRemove} aria-label={t('Remove ','সরান: ')+file.name}><X size={18} aria-hidden="true"/></button></li>;
}
export function MultiFilePicker({files,onChange,maxFiles=20,maxMB=10,disabled=false,label}:{files:File[];onChange:(files:File[])=>void;maxFiles?:number;maxMB?:number;disabled?:boolean;label?:string}){
 const {lang,t}=useI18n();const id=useId();const [error,setError]=useState('');const reduced=useReducedMotion();
 const limit=Math.min(20,Math.max(1,maxFiles));
 const errorText=error.startsWith('You can attach')?t(error,`সর্বোচ্চ ${formatNumber(limit,lang)}টি ফাইল যুক্ত করা যাবে। আরও ফাইল যোগ করতে একটি সরান।`):error.startsWith('Total attachment size')?t(error,`সব ফাইলের মোট আকার ${formatNumber(MAX_ATTACHMENT_TOTAL_MB,lang)} এমবির বেশি হতে পারবে না। আগের নির্বাচিত ফাইলগুলো রাখা হয়েছে।`):t(error,`খালি নয় এমন JPG, PNG, WebP বা PDF ফাইল বাছুন, প্রতিটি সর্বোচ্চ ${formatNumber(maxMB,lang)} এমবি। আগের নির্বাচিত ফাইলগুলো রাখা হয়েছে।`);
 return <LazyMotion features={domAnimation}><section className="multi-file-picker" aria-labelledby={id+'-label'}><div className="attachment-heading"><Images size={23} aria-hidden="true"/><div><h3 id={id+'-label'}>{label||t('Photos, screenshots or documents','ছবি, স্ক্রিনশট বা নথি')}</h3><p>{t(`Choose up to ${limit} files. You can add more in separate selections.`,`সর্বোচ্চ ${formatNumber(limit,lang)}টি ফাইল বাছুন। একাধিকবার বেছে নতুন ফাইল যোগ করতে পারেন।`)}</p></div><span aria-live="polite">{formatNumber(files.length,lang)}/{formatNumber(limit,lang)}</span></div><label className="attachment-input-label" htmlFor={id}><Plus size={18} aria-hidden="true"/>{t('Add photos or documents','ছবি বা নথি যোগ করুন')}</label><input id={id} type="file" disabled={disabled} multiple accept="image/*,.pdf,.jpg,.jpeg,.png,.webp,.gif,.svg,.avif,.bmp" aria-describedby={id+'-help'+(error?' '+id+'-error':'')} onChange={e=>{const picked=Array.from(e.target.files||[]);e.target.value='';if(!picked.length)return;const result=selectAttachments(files,picked,limit,maxMB);setError(result.error);if(!result.error)onChange(result.files);}}/><p id={id+'-help'} className="attachment-privacy"><LockKeyhole size={15} aria-hidden="true"/>{t(`Staff verification · JPG, PNG, WebP or PDF · ${maxMB} MB each · ${MAX_ATTACHMENT_TOTAL_MB} MB combined. Files are uploaded only when you submit.`,`যাচাইকরণের জন্য · JPG, PNG, WebP বা PDF · প্রতিটি ${formatNumber(maxMB,lang)} এমবি · সব মিলিয়ে ${formatNumber(MAX_ATTACHMENT_TOTAL_MB,lang)} এমবি। জমা দিলেই ফাইল আপলোড হবে।`)}</p>{error&&<p id={id+'-error'} role="alert" className="attachment-error">{errorText}</p>}<m.ul className="attachment-grid" initial={false} animate={{opacity:1}} transition={{duration:reduced?0:.15}}>{files.map((file,index)=><Attachment key={file.name+file.size+file.lastModified} file={file} disabled={disabled} onRemove={()=>{if(disabled)return;onChange(files.filter((_,i)=>i!==index));setError('');}}/>)}</m.ul></section></LazyMotion>;
}
