"use client";

import {useEffect,useState} from 'react';
import {useAuth} from '../features/auth/AuthContext';
import {api,apiFileUrl} from '../services/api';
import './ui/add-organization.css';

type ImageRequest={id:number;business_id:number;name:string;location:string;business_status:string;consent_confirmed:boolean};

function ImageDecision({image,isAdmin,onDecided}:{image:ImageRequest;isAdmin:boolean;onDecided:()=>void}){
  const[preview,setPreview]=useState('');const[reason,setReason]=useState('');const[confirmed,setConfirmed]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const decide=async(status:'approved'|'rejected')=>{setBusy(true);setMessage('');try{await api(`/admin/organization-images/${image.id}`,'PATCH',{status,reason,public_display_confirmed:confirmed});onDecided();}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}};
  return <article className="workspace-comment organization-image-review"><h3>{image.name}</h3><p>{image.location||'No address supplied'} · Organization #{image.business_id} · {image.business_status}</p><p>Publication permission: {image.consent_confirmed?'confirmed by submitter':'missing'}. A profile image approval does not verify ownership or service quality.</p><button type="button" className="btn-pill-light" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{const response=await fetch(apiFileUrl(`/admin/organization-images/${image.id}/preview`),{credentials:'include',headers:{Accept:'image/jpeg,image/png,image/webp,application/json'}});if(!response.ok){const result=await response.json().catch(()=>({message:'Preview unavailable.'}));throw new Error(result.message);}const blob=await response.blob();setPreview(URL.createObjectURL(blob));}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}>{busy?'Checking…':'Open scanned private preview'}</button>{preview&&<img src={preview} alt={`Private profile image awaiting approval for ${image.name}`} className="organization-image-staff-preview"/>}{isAdmin&&<><label className="review-label">Image decision reason<textarea className="review-textarea" value={reason} minLength={10} maxLength={2000} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="organization-image-consent"><input type="checkbox" checked={confirmed} disabled={busy||!preview} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed the image and permission. It identifies this organization and contains no private documents or personal information.</span></label><div className="workspace-tabs"><button type="button" className="btn-pill-light" disabled={busy||!preview||!confirmed||reason.trim().length<10||!image.consent_confirmed} onClick={()=>decide('approved')}>Approve public image</button><button type="button" className="btn-pill-light" disabled={busy||reason.trim().length<10} onClick={()=>decide('rejected')}>Reject image</button></div></>}<p role="status">{message}</p></article>;
}

export function OrganizationImageDesk(){
  const{user}=useAuth();const[items,setItems]=useState<ImageRequest[]>([]);const[loaded,setLoaded]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  if(!user||!['admin','moderator'].includes(user.role))return null;
  return <details className="workspace-card"><summary>Organization profile images</summary><p>Uploads are private until an admin records an explicit image approval. Review the scanned preview and publication permission before deciding.</p><button type="button" className="btn-pill-light" disabled={busy} onClick={async()=>{setBusy(true);setMessage('');try{const result=await api<{data:ImageRequest[]}>('/admin/organization-images');setItems(result.data);setLoaded(true);}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}>{busy?'Loading…':'Load pending images'}</button>{loaded&&!items.length&&<p>No images awaiting approval.</p>}{items.map(image=><ImageDecision key={image.id} image={image} isAdmin={user.role==='admin'} onDecided={()=>{setItems(current=>current.filter(item=>item.id!==image.id));setMessage('Image decision recorded. Organization ownership and listing approval are unchanged.');}}/>)}<p role="status">{message}</p></details>;
}
