<?php

namespace Database\Seeders;

use App\Models\Business;
use App\Models\Review;
use Illuminate\Database\Seeder;

/**
 * BusinessSeeder
 * Populates authentic, real-world Bangladesh entities across all 8 administrative divisions:
 * Dhaka, Chattogram, Rajshahi, Khulna, Sylhet, Barishal, Rangpur, and Mymensingh.
 * Covers Hospitals, Universities, Products, Couriers, Doctors, Consultancies, and E-Commerce.
 */
class BusinessSeeder extends Seeder
{
    public function run(): void
    {
        $entities = [
            // ==========================================
            // DHAKA DIVISION
            // ==========================================
            [
                'slug' => 'square-hospital-ltd',
                'name' => 'Square Hospital Ltd.',
                'bengali_name' => 'স্কয়ার হাসপাতাল লিমিটেড',
                'category' => 'Hospitals & Clinics',
                'description' => 'Multispecialty tertiary care hospital in Dhaka with 24/7 emergency response, modern ICUs, and specialized medical departments.',
                'location' => 'West Panthapath, Dhaka',
                'rating' => 4.3,
                'review_count' => 184,
                'verified' => true,
                'phone' => '10616',
                'website' => 'https://squarehospital.com',
                'facebook_url' => 'https://facebook.com/squarehospitalbd',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Panthapath Main Hospital', 'Uttara Consultation Center'],
            ],
            [
                'slug' => 'evercare-hospital-dhaka',
                'name' => 'Evercare Hospital Dhaka',
                'bengali_name' => 'এভারকেয়ার হাসপাতাল ঢাকা',
                'category' => 'Hospitals & Clinics',
                'description' => 'JCI-accredited super-specialty hospital in Bashundhara providing cutting-edge healthcare, oncology, cardiology, and transplant services.',
                'location' => 'Plot 81, Block E, Bashundhara R/A, Dhaka',
                'rating' => 4.5,
                'review_count' => 260,
                'verified' => true,
                'phone' => '10678',
                'website' => 'https://evercarebd.com',
                'facebook_url' => 'https://facebook.com/EvercareHospitalDhaka',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Bashundhara R/A Main Hospital'],
            ],
            [
                'slug' => 'united-hospital-limited',
                'name' => 'United Hospital Limited',
                'bengali_name' => 'ইউনাইটেড হাসপাতাল লিমিটেড',
                'category' => 'Hospitals & Clinics',
                'description' => 'Premium 500-bed multispecialty hospital in Gulshan known for international standard cardiac, neuro, and renal care units.',
                'location' => 'Plot 15, Road 71, Gulshan 2, Dhaka',
                'rating' => 4.4,
                'review_count' => 195,
                'verified' => true,
                'phone' => '10666',
                'website' => 'https://medix.com.bd',
                'facebook_url' => 'https://facebook.com/UnitedHospitalLtd',
                'color' => '#059669',
                'image' => null,
                'branches' => ['Gulshan Main Hospital', 'Dhanmondi Consultation Wing'],
            ],
            [
                'slug' => 'bsmmu-dhaka',
                'name' => 'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
                'bengali_name' => 'বঙ্গবন্ধু শেখ মুজিব মেডিক্যাল বিশ্ববিদ্যালয়',
                'category' => 'Hospitals & Clinics',
                'description' => 'Premier public medical university and tertiary referral hospital providing specialized treatments, super-specialty care, and postgraduate medical education.',
                'location' => 'Shahbagh, Dhaka',
                'rating' => 4.2,
                'review_count' => 430,
                'verified' => true,
                'phone' => '02-9661051',
                'website' => 'https://bsmmu.edu.bd',
                'facebook_url' => 'https://facebook.com/bsmmu.official',
                'color' => '#dc2626',
                'image' => null,
                'branches' => ['Shahbagh Central Complex', 'Super Specialized Hospital Wing'],
            ],
            [
                'slug' => 'university-of-dhaka',
                'name' => 'University of Dhaka',
                'bengali_name' => 'ঢাকা বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'The highest seat of learning in Bangladesh, established in 1921, fostering higher education, scientific research, and national leadership.',
                'location' => 'Nilkhet Road, Dhaka 1000',
                'rating' => 4.6,
                'review_count' => 520,
                'verified' => true,
                'phone' => '02-9661900',
                'website' => 'https://du.ac.bd',
                'facebook_url' => 'https://facebook.com/dhakauniversity.official',
                'color' => '#7c3aed',
                'image' => null,
                'branches' => ['Main Campus Nilkhet', 'Curzon Hall Science Complex'],
            ],
            [
                'slug' => 'buet-dhaka',
                'name' => 'Bangladesh University of Engineering and Technology (BUET)',
                'bengali_name' => 'বাংলাদেশ প্রকৌশল বিশ্ববিদ্যালয় (বুয়েট)',
                'category' => 'Universities & Education',
                'description' => 'The foremost technical institution in Bangladesh, renowned for engineering, architecture, and technological innovation.',
                'location' => 'Palashi, Dhaka 1000',
                'rating' => 4.9,
                'review_count' => 610,
                'verified' => true,
                'phone' => '02-55167100',
                'website' => 'https://buet.ac.bd',
                'facebook_url' => 'https://facebook.com/buet.official',
                'color' => '#b91c1c',
                'image' => null,
                'branches' => ['Palashi Main Campus'],
            ],
            [
                'slug' => 'north-south-university',
                'name' => 'North South University (NSU)',
                'bengali_name' => 'নর্থ সাউথ ইউনিভার্সিটি',
                'category' => 'Universities & Education',
                'description' => 'First government-approved private university in Bangladesh with world-class faculty, accredited business school, and modern engineering labs.',
                'location' => 'Plot 15, Block B, Bashundhara R/A, Dhaka',
                'rating' => 4.5,
                'review_count' => 380,
                'verified' => true,
                'phone' => '02-55668200',
                'website' => 'https://northsouth.edu',
                'facebook_url' => 'https://facebook.com/NorthSouthUniversity',
                'color' => '#1e3a8a',
                'image' => null,
                'branches' => ['Bashundhara Main Campus'],
            ],
            [
                'slug' => 'brac-university',
                'name' => 'BRAC University',
                'bengali_name' => 'ব্র্যাক বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Progressive higher education institution with a green campus in Merul Badda, recognized for research in technology, public health, and law.',
                'location' => 'Kha 224, Bir Uttam Rafiqul Islam Ave, Merul Badda, Dhaka',
                'rating' => 4.6,
                'review_count' => 310,
                'verified' => true,
                'phone' => '09666710000',
                'website' => 'https://bracu.ac.bd',
                'facebook_url' => 'https://facebook.com/BRACUniversity',
                'color' => '#0d9488',
                'image' => null,
                'branches' => ['Merul Badda Campus', 'TARC Savar Residential Campus'],
            ],
            [
                'slug' => 'star-tech-engineering',
                'name' => 'Star Tech & Engineering',
                'bengali_name' => 'স্টার টেক অ্যান্ড ইঞ্জিনিয়ারিং',
                'category' => 'Online Electronics Shop',
                'description' => 'Leading computer hardware, laptop, gadget retailer, and official component distributor with physical stores across Bangladesh.',
                'location' => 'Multiplan Center, Elephant Road, Dhaka',
                'rating' => 4.6,
                'review_count' => 480,
                'verified' => true,
                'phone' => '09678-002003',
                'website' => 'https://startech.com.bd',
                'facebook_url' => 'https://facebook.com/star.tech.com.bd',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Elephant Road', 'IDB Bhaban', 'Uttara', 'Chittagong GEC', 'Rajshahi Alokar Mor'],
            ],
            [
                'slug' => 'ryans-computers',
                'name' => 'Ryans Computers Limited',
                'bengali_name' => 'রায়ান্স কম্পিউটার্স লিমিটেড',
                'category' => 'Online Electronics Shop',
                'description' => 'Pioneer IT retail chain with transparent pricing, official manufacturer warranties, and nationwide branch delivery.',
                'location' => 'IDB Bhaban, Rokeya Sarani, Agargaon, Dhaka',
                'rating' => 4.5,
                'review_count' => 390,
                'verified' => true,
                'phone' => '09604-442121',
                'website' => 'https://ryans.com',
                'facebook_url' => 'https://facebook.com/ryanscomputers',
                'color' => '#ea580c',
                'image' => null,
                'branches' => ['IDB Bhaban Agargaon', 'Elephant Road', 'Banani', 'Agrabad Chattogram'],
            ],
            [
                'slug' => 'walton-hi-tech-industries',
                'name' => 'Walton Hi-Tech Industries PLC',
                'bengali_name' => 'ওয়ালটন হাই-টেক ইন্ডাস্ট্রিজ পিএলসি',
                'category' => 'Products',
                'description' => 'Conglomerate manufacturing refrigerators, air conditioners, televisions, smartphones, and domestic smart electronics in Bangladesh.',
                'location' => 'Chandra, Gazipur, Dhaka',
                'rating' => 4.4,
                'review_count' => 550,
                'verified' => true,
                'phone' => '09612-316267',
                'website' => 'https://waltonbd.com',
                'facebook_url' => 'https://facebook.com/Waltonbd',
                'color' => '#2563eb',
                'image' => null,
                'branches' => ['Gazipur Manufacturing Plant', 'Walton Plaza Pan-Bangladesh'],
            ],
            [
                'slug' => 'pathao-courier',
                'name' => 'Pathao Courier',
                'bengali_name' => 'পাঠাও কুরিয়ার',
                'category' => 'Courier & Digital Services',
                'description' => 'Fast nationwide parcel delivery, merchant cash-on-delivery tracking, and end-to-end e-commerce logistics network.',
                'location' => 'Gulshan 1, Dhaka',
                'rating' => 4.0,
                'review_count' => 410,
                'verified' => true,
                'phone' => '09610-003030',
                'website' => 'https://pathao.com/courier',
                'facebook_url' => 'https://facebook.com/pathaoapp',
                'color' => '#dc2626',
                'image' => null,
                'branches' => ['Dhaka Central Logistics Hub', 'Chattogram Hub', 'Sylhet Hub', 'Bogura Hub'],
            ],
            [
                'slug' => 'bkash-limited',
                'name' => 'bKash Limited',
                'bengali_name' => 'বিকাশ লিমিটেড',
                'category' => 'Businesses & Services',
                'description' => 'Largest Mobile Financial Service (MFS) provider in Bangladesh enabling instant cash transfers, bill payments, and merchant transactions.',
                'location' => 'Shadhinata Bhaban, 8 Bir Sreshtho Shahid Ruhul Amin Sarani, Dhaka',
                'rating' => 4.7,
                'review_count' => 780,
                'verified' => true,
                'phone' => '16247',
                'website' => 'https://bkash.com',
                'facebook_url' => 'https://facebook.com/bkashlimited',
                'color' => '#e11d48',
                'image' => null,
                'branches' => ['Headquarters Dhaka', 'Customer Service Centers in all 64 Districts'],
            ],
            [
                'slug' => 'dr-abm-abdullah',
                'name' => 'Prof. Dr. ABM Abdullah',
                'bengali_name' => 'অধ্যাপক ডা. এ বি এম আবদুল্লাহ',
                'category' => 'Doctors & Professionals',
                'description' => 'Eminent Medicine Specialist, Emeritus Professor, and personal physician to heads of state with over four decades of clinical experience.',
                'location' => 'Green Life Hospital, Green Road, Dhaka',
                'rating' => 4.9,
                'review_count' => 340,
                'verified' => true,
                'phone' => '01711-537446',
                'website' => 'https://greenlifehospital.com.bd',
                'facebook_url' => 'https://facebook.com/drabmabdullah',
                'color' => '#059669',
                'image' => null,
                'branches' => ['Green Life Hospital Chamber'],
            ],
            [
                'slug' => 'daraz-bangladesh',
                'name' => 'Daraz Bangladesh',
                'bengali_name' => 'দারাজ বাংলাদেশ',
                'category' => 'E-Commerce Marketplace',
                'description' => 'Largest online shopping destination in Bangladesh featuring millions of products, buyer protection, and nationwide door-to-door delivery.',
                'location' => 'Asfia Tower, Road 11, Banani, Dhaka',
                'rating' => 4.1,
                'review_count' => 620,
                'verified' => true,
                'phone' => '16492',
                'website' => 'https://daraz.com.bd',
                'facebook_url' => 'https://facebook.com/DarazBangladesh',
                'color' => '#f97316',
                'image' => null,
                'branches' => ['Banani Central Office', 'Tejgaon Fulfillment Center', 'Nationwide Hubs'],
            ],
            [
                'slug' => 'chaldal-limited',
                'name' => 'Chaldal Limited',
                'bengali_name' => 'চালডাল লিমিটেড',
                'category' => 'E-Commerce Marketplace',
                'description' => 'Leading online grocery delivery service in Dhaka, Chattogram and Jashore offering 1-hour fast doorstep delivery.',
                'location' => 'Tejgaon Industrial Area, Dhaka',
                'rating' => 4.6,
                'review_count' => 310,
                'verified' => true,
                'phone' => '09643-242532',
                'website' => 'https://chaldal.com',
                'facebook_url' => 'https://facebook.com/chaldalcom',
                'color' => '#84cc16',
                'image' => null,
                'branches' => ['Tejgaon Warehouse', 'Uttara Hub', 'Dhanmondi Hub', 'Chattogram Warehouse'],
            ],
            [
                'slug' => 'idp-education-bangladesh',
                'name' => 'IDP Education Bangladesh',
                'bengali_name' => 'আইডিপি এডুকেশন বাংলাদেশ',
                'category' => 'Overseas Education Consultancy',
                'description' => 'Official co-owner of IELTS and trusted student placement service for top universities in Australia, UK, USA, Canada, and Ireland.',
                'location' => 'Hamid Tower, Gulshan Circle 2, Dhaka',
                'rating' => 4.7,
                'review_count' => 280,
                'verified' => true,
                'phone' => '09666-782782',
                'website' => 'https://idp.com/bangladesh',
                'facebook_url' => 'https://facebook.com/idpbangladesh',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Gulshan Office', 'Dhanmondi Office', 'Chattogram Agrabad Office'],
            ],
            [
                'slug' => 'aarong-brac',
                'name' => 'Aarong (BRAC Enterprises)',
                'bengali_name' => 'আড়ং',
                'category' => 'Products',
                'description' => 'Social enterprise celebrating Bangladeshi craftsmanship with artisan textiles, apparel, handmade jewelry, and organic lifestyle collections.',
                'location' => 'Aarong Centre, 34 Jamalpur Twin Towers, Tejgaon, Dhaka',
                'rating' => 4.7,
                'review_count' => 490,
                'verified' => true,
                'phone' => '09678-444777',
                'website' => 'https://aarong.com',
                'facebook_url' => 'https://facebook.com/aarong',
                'color' => '#b45309',
                'image' => null,
                'branches' => ['Dhanmondi Outlet', 'Uttara Outlet', 'Gulshan Outlet', 'Chattogram Sholashahar'],
            ],
            [
                'slug' => 'apex-footwear-ltd',
                'name' => 'Apex Footwear Ltd.',
                'bengali_name' => 'অ্যাপেক্স ফুটওয়্যার লিমিটেড',
                'category' => 'Products',
                'description' => 'Foremost leather goods and footwear manufacturer and retailer in Bangladesh with hundreds of outlets countrywide.',
                'location' => 'House 6, Road 137, Block SE(D), Gulshan 1, Dhaka',
                'rating' => 4.3,
                'review_count' => 210,
                'verified' => true,
                'phone' => '09612-002244',
                'website' => 'https://apexfootwear.com',
                'facebook_url' => 'https://facebook.com/apexfootwear',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Gulshan', 'Dhanmondi', 'Mirpur', 'Chittagong GEC', 'Sylhet Zindabazar'],
            ],

            // ==========================================
            // CHATTOGRAM DIVISION
            // ==========================================
            [
                'slug' => 'evercare-hospital-chattogram',
                'name' => 'Evercare Hospital Chattogram',
                'bengali_name' => 'এভারকেয়ার হাসপাতাল চট্টগ্রাম',
                'category' => 'Hospitals & Clinics',
                'description' => 'The premier 470-bed tertiary multispecialty hospital in port city Chattogram featuring state-of-the-art diagnostic and surgical infrastructure.',
                'location' => 'Plot H1, Ananya Residential Area, Oxygen-Kuaish Road, Chattogram',
                'rating' => 4.6,
                'review_count' => 175,
                'verified' => true,
                'phone' => '10678',
                'website' => 'https://evercarebd.com/chattogram',
                'facebook_url' => 'https://facebook.com/EvercareHospitalChattogram',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Ananya R/A Main Hospital'],
            ],
            [
                'slug' => 'chittagong-medical-college-hospital',
                'name' => 'Chittagong Medical College Hospital (CMCH)',
                'bengali_name' => 'চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => 'Major tertiary medical institution providing extensive healthcare and emergency trauma response to millions across south-eastern Bangladesh.',
                'location' => '57 K.B. Fazlul Kader Road, Panchlaish, Chattogram',
                'rating' => 4.1,
                'review_count' => 380,
                'verified' => true,
                'phone' => '031-616382',
                'website' => 'https://cmch.gov.bd',
                'facebook_url' => 'https://facebook.com/cmch.bd',
                'color' => '#047857',
                'image' => null,
                'branches' => ['Panchlaish Central Campus'],
            ],
            [
                'slug' => 'university-of-chittagong',
                'name' => 'University of Chittagong (CU)',
                'bengali_name' => 'চট্টগ্রাম বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Expansive public university nestled in green scenic hills of Hathazari, acclaimed for marine science, arts, business and forestry research.',
                'location' => 'Hathazari, Chattogram 4331',
                'rating' => 4.7,
                'review_count' => 410,
                'verified' => true,
                'phone' => '031-2606001',
                'website' => 'https://cu.ac.bd',
                'facebook_url' => 'https://facebook.com/University.Of.Chittagong',
                'color' => '#15803d',
                'image' => null,
                'branches' => ['Main Campus Hathazari', 'Sholoshohor Transit Campus'],
            ],
            [
                'slug' => 'cuet-chattogram',
                'name' => 'Chittagong University of Engineering & Technology (CUET)',
                'bengali_name' => 'চট্টগ্রাম প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Public technical university situated in Raozan, focused on civil, electrical, mechanical, and petroleum engineering education.',
                'location' => 'Pahartali, Raozan, Chattogram 4349',
                'rating' => 4.6,
                'review_count' => 240,
                'verified' => true,
                'phone' => '031-714946',
                'website' => 'https://cuet.ac.bd',
                'facebook_url' => 'https://facebook.com/cuet.official',
                'color' => '#b91c1c',
                'image' => null,
                'branches' => ['Raozan Campus'],
            ],
            [
                'slug' => 'bsrm-steels-limited',
                'name' => 'BSRM Steels Limited',
                'bengali_name' => 'বিএসআরএম স্টিলস লিমিটেড',
                'category' => 'Products',
                'description' => 'The leading steel manufacturing company in Bangladesh, producing high-grade rebar and structural steel for iconic national megaprojects.',
                'location' => 'Ali Mansion, 1207/1099 Sadarghat Road, Chattogram',
                'rating' => 4.7,
                'review_count' => 290,
                'verified' => true,
                'phone' => '031-2854901',
                'website' => 'https://bsrm.com',
                'facebook_url' => 'https://facebook.com/bsrmsteels',
                'color' => '#4338ca',
                'image' => null,
                'branches' => ['Corporate Office Chattogram', 'Mirsharai Rolling Mill', 'Dhaka Corporate Branch'],
            ],
            [
                'slug' => 'sundarban-courier-chattogram',
                'name' => 'Sundarban Courier Service (Agrabad)',
                'bengali_name' => 'সুন্দরবন কুরিয়ার সার্ভিস (আগ্রাবাদ)',
                'category' => 'Courier & Digital Services',
                'description' => 'One of the oldest and most extensive express parcel, document, and cargo delivery networks in the Chittagong commercial division.',
                'location' => 'Agrabad Commercial Area, Chattogram',
                'rating' => 3.9,
                'review_count' => 210,
                'verified' => true,
                'phone' => '031-712890',
                'website' => 'https://sundarbancourierltd.com',
                'facebook_url' => 'https://facebook.com/sundarbancourier',
                'color' => '#ca8a04',
                'image' => null,
                'branches' => ['Agrabad Hub', 'GEC Branch', 'Muradpur Branch', 'Cox’s Bazar Branch'],
            ],
            [
                'slug' => 'comilla-university',
                'name' => 'Comilla University',
                'bengali_name' => 'কুমিল্লা বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Public university in Kotbari, Cumilla, providing academic disciplines in science, engineering, business, and social sciences.',
                'location' => 'Kotbari, Cumilla, Chattogram',
                'rating' => 4.3,
                'review_count' => 190,
                'verified' => true,
                'phone' => '081-73920',
                'website' => 'https://cou.ac.bd',
                'facebook_url' => 'https://facebook.com/ComillaUniversityOfficial',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Kotbari Campus'],
            ],

            // ==========================================
            // RAJSHAHI DIVISION
            // ==========================================
            [
                'slug' => 'rajshahi-medical-college-hospital',
                'name' => 'Rajshahi Medical College Hospital (RMCH)',
                'bengali_name' => 'রাজশাহী মেডিকেল কলেজ হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => 'The largest government healthcare facility in northern Bangladesh with 1,200 beds, coronary care, and advanced surgical facilities.',
                'location' => 'Laxmipur, Rajshahi 6000',
                'rating' => 4.2,
                'review_count' => 310,
                'verified' => true,
                'phone' => '0721-772150',
                'website' => 'https://rmc.ac.bd',
                'facebook_url' => 'https://facebook.com/rmch.rajshahi',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Laxmipur Complex'],
            ],
            [
                'slug' => 'university-of-rajshahi',
                'name' => 'University of Rajshahi (RU)',
                'bengali_name' => 'রাজশাহী বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Second oldest public university in Bangladesh, famous for its picturesque 753-acre Paris Road campus and vibrant scientific research.',
                'location' => 'Motihar, Rajshahi 6205',
                'rating' => 4.8,
                'review_count' => 470,
                'verified' => true,
                'phone' => '0721-750041',
                'website' => 'https://ru.ac.bd',
                'facebook_url' => 'https://facebook.com/rajshahiuniversity.official',
                'color' => '#166534',
                'image' => null,
                'branches' => ['Motihar Main Campus'],
            ],
            [
                'slug' => 'ruet-rajshahi',
                'name' => 'Rajshahi University of Engineering & Technology (RUET)',
                'bengali_name' => 'রাজশাহী প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Prestigious public engineering university in north Bengal known for civil, computer science, and electrical engineering leadership.',
                'location' => 'Kazla, Rajshahi 6204',
                'rating' => 4.7,
                'review_count' => 280,
                'verified' => true,
                'phone' => '0721-750105',
                'website' => 'https://ruet.ac.bd',
                'facebook_url' => 'https://facebook.com/ruet.ac.bd',
                'color' => '#991b1b',
                'image' => null,
                'branches' => ['Kazla Campus'],
            ],
            [
                'slug' => 'shaheed-ziaur-rahman-medical-college-bogura',
                'name' => 'Shaheed Ziaur Rahman Medical College Hospital',
                'bengali_name' => 'শহীদ জিয়াউর রহমান মেডিকেল কলেজ হাসপাতাল (বগুড়া)',
                'category' => 'Hospitals & Clinics',
                'description' => '500-bed government tertiary referral hospital serving the greater Bogura, Joypurhat, and Naogaon regional districts.',
                'location' => 'Silimpur, Bogra, Rajshahi',
                'rating' => 4.1,
                'review_count' => 220,
                'verified' => true,
                'phone' => '051-69004',
                'website' => 'https://szmc.gov.bd',
                'facebook_url' => 'https://facebook.com/szmch.bogra',
                'color' => '#047857',
                'image' => null,
                'branches' => ['Silimpur Main Hospital'],
            ],
            [
                'slug' => 'star-tech-rajshahi',
                'name' => 'Star Tech & Engineering (Rajshahi)',
                'bengali_name' => 'স্টার টেক (রাজশাহী শাখা)',
                'category' => 'Online Electronics Shop',
                'description' => 'Full-service IT store and repair hub providing desktop PCs, gaming laptops, and accessories to students and enterprises in Rajshahi.',
                'location' => 'Alokar Mor, New Market, Rajshahi',
                'rating' => 4.6,
                'review_count' => 140,
                'verified' => true,
                'phone' => '09678-002003',
                'website' => 'https://startech.com.bd',
                'facebook_url' => 'https://facebook.com/star.tech.com.bd',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Rajshahi Alokar Mor Branch'],
            ],

            // ==========================================
            // KHULNA DIVISION
            // ==========================================
            [
                'slug' => 'khulna-city-medical-college-hospital',
                'name' => 'Khulna City Medical College & Hospital',
                'bengali_name' => 'খুলনা সিটি মেডিকেল কলেজ ও হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => 'Modern private tertiary medical center equipped with modern diagnostic cath lab, ICU, and neonatal intensive care in southwest Bangladesh.',
                'location' => '33 KDA Avenue, Khulna 9100',
                'rating' => 4.4,
                'review_count' => 165,
                'verified' => true,
                'phone' => '041-721950',
                'website' => 'https://kcmc.edu.bd',
                'facebook_url' => 'https://facebook.com/kcmch.official',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['KDA Avenue Hospital Complex'],
            ],
            [
                'slug' => 'khulna-university',
                'name' => 'Khulna University (KU)',
                'bengali_name' => 'খুলনা বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Top-ranking public university renowned for its student-politics-free environment, biotechnology, architecture, and environmental studies.',
                'location' => 'Gollamari, Khulna 9208',
                'rating' => 4.8,
                'review_count' => 370,
                'verified' => true,
                'phone' => '041-720171',
                'website' => 'https://ku.ac.bd',
                'facebook_url' => 'https://facebook.com/KhulnaUniversityOfficial',
                'color' => '#047857',
                'image' => null,
                'branches' => ['Gollamari Campus'],
            ],
            [
                'slug' => 'kuet-khulna',
                'name' => 'Khulna University of Engineering & Technology (KUET)',
                'bengali_name' => 'খুলনা প্রকৌশল ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Premier public engineering university in south-western Bangladesh offering degrees in advanced robotics, mechatronics, and civil engineering.',
                'location' => 'Teligati, Fulbarigate, Khulna 9203',
                'rating' => 4.7,
                'review_count' => 295,
                'verified' => true,
                'phone' => '041-769468',
                'website' => 'https://kuet.ac.bd',
                'facebook_url' => 'https://facebook.com/kuet.ac.bd',
                'color' => '#7f1d1d',
                'image' => null,
                'branches' => ['Teligati Main Campus'],
            ],
            [
                'slug' => 'jashore-university-of-science-and-technology',
                'name' => 'Jashore University of Science and Technology (JUST)',
                'bengali_name' => 'যশোর বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Dynamic public science and technological institution specializing in genetic engineering, agro-technology, and biomedical research.',
                'location' => 'Churamonkathi, Jashore, Khulna',
                'rating' => 4.5,
                'review_count' => 190,
                'verified' => true,
                'phone' => '02477-761154',
                'website' => 'https://just.edu.bd',
                'facebook_url' => 'https://facebook.com/just.edu.bd',
                'color' => '#0369a1',
                'image' => null,
                'branches' => ['Jashore Campus'],
            ],
            [
                'slug' => 'sundarban-courier-khulna',
                'name' => 'Sundarban Courier Service (Khulna)',
                'bengali_name' => 'সুন্দরবন কুরিয়ার সার্ভিস (খুলনা)',
                'category' => 'Courier & Digital Services',
                'description' => 'Central dispatch depot and logistics transport point covering all coastal and delta districts in Khulna Division.',
                'location' => 'KDA Avenue, Sonadanga, Khulna',
                'rating' => 4.0,
                'review_count' => 170,
                'verified' => true,
                'phone' => '041-731200',
                'website' => 'https://sundarbancourierltd.com',
                'facebook_url' => 'https://facebook.com/sundarbancourier',
                'color' => '#ca8a04',
                'image' => null,
                'branches' => ['Sonadanga Regional Hub'],
            ],

            // ==========================================
            // SYLHET DIVISION
            // ==========================================
            [
                'slug' => 'mount-adora-hospital-sylhet',
                'name' => 'Mount Adora Hospital',
                'bengali_name' => 'মাউন্ট এডোরা হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => 'Modern healthcare facility in Sylhet offering advanced surgical procedures, CCU, dialysis, and emergency pediatric treatments.',
                'location' => 'Nayasarak, Mirboxtula Road, Sylhet',
                'rating' => 4.5,
                'review_count' => 210,
                'verified' => true,
                'phone' => '01798-755755',
                'website' => 'https://mountadora.com',
                'facebook_url' => 'https://facebook.com/mountadorahospital',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Nayasarak Branch', 'Akhalia Branch, Sylhet'],
            ],
            [
                'slug' => 'sylhet-mag-osmani-medical-college-hospital',
                'name' => 'Sylhet MAG Osmani Medical College Hospital',
                'bengali_name' => 'সিলেট এম এ জি ওসমানী মেডিকেল কলেজ হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => 'The largest government medical institution in north-eastern Bangladesh, providing subsidized healthcare and residency training.',
                'location' => 'Kajalshah, Sylhet 3100',
                'rating' => 4.2,
                'review_count' => 340,
                'verified' => true,
                'phone' => '0821-713487',
                'website' => 'https://magomc.edu.bd',
                'facebook_url' => 'https://facebook.com/magomch.sylhet',
                'color' => '#047857',
                'image' => null,
                'branches' => ['Kajalshah Hospital Complex'],
            ],
            [
                'slug' => 'sust-sylhet',
                'name' => 'Shahjalal University of Science and Technology (SUST)',
                'bengali_name' => 'শাহজালাল বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Top public science university in Bangladesh, famous for pioneer SMS admissions, software engineering, robotics, and natural gas research.',
                'location' => 'Kumargaon, Sylhet 3114',
                'rating' => 4.8,
                'review_count' => 460,
                'verified' => true,
                'phone' => '0821-713850',
                'website' => 'https://sust.edu',
                'facebook_url' => 'https://facebook.com/SUSTOfficial',
                'color' => '#1e3a8a',
                'image' => null,
                'branches' => ['Kumargaon Campus'],
            ],
            [
                'slug' => 'star-tech-sylhet',
                'name' => 'Star Tech & Engineering (Sylhet)',
                'bengali_name' => 'স্টার টেক (সিলেট শাখা)',
                'category' => 'Online Electronics Shop',
                'description' => 'Official brand showroom for laptops, PC hardware, Apple accessories, and printers located in central Sylhet city.',
                'location' => 'Al-Hamra Shopping City, Zindabazar, Sylhet',
                'rating' => 4.6,
                'review_count' => 150,
                'verified' => true,
                'phone' => '09678-002003',
                'website' => 'https://startech.com.bd',
                'facebook_url' => 'https://facebook.com/star.tech.com.bd',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Zindabazar Branch'],
            ],

            // ==========================================
            // BARISHAL DIVISION
            // ==========================================
            [
                'slug' => 'sher-e-bangla-medical-college-hospital-barishal',
                'name' => 'Sher-e-Bangla Medical College Hospital (SBMCH)',
                'bengali_name' => 'শের-ই-বাংলা মেডিকেল কলেজ হাসপাতাল (বরিশাল)',
                'category' => 'Hospitals & Clinics',
                'description' => 'The primary government tertiary medical college and general hospital serving the coastal districts of the southern Barishal Division.',
                'location' => 'Band Road, Barishal 8200',
                'rating' => 4.1,
                'review_count' => 290,
                'verified' => true,
                'phone' => '0431-217354',
                'website' => 'https://sbmch.gov.bd',
                'facebook_url' => 'https://facebook.com/sbmch.barisal',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Band Road Hospital Complex'],
            ],
            [
                'slug' => 'university-of-barishal',
                'name' => 'University of Barishal',
                'bengali_name' => 'বরিশাল বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Major public university on the scenic banks of the Kirtankhola river, offering programs in coastal science, geology, and business administration.',
                'location' => 'Kornokathi, Barishal 8200',
                'rating' => 4.5,
                'review_count' => 230,
                'verified' => true,
                'phone' => '0431-217743',
                'website' => 'https://bu.ac.bd',
                'facebook_url' => 'https://facebook.com/barishaluniversity.official',
                'color' => '#0369a1',
                'image' => null,
                'branches' => ['Kornokathi Main Campus'],
            ],
            [
                'slug' => 'pstu-patuakhali',
                'name' => 'Patuakhali Science and Technology University (PSTU)',
                'bengali_name' => 'পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Higher education center in southern coastal Bangladesh leading breakthroughs in disaster resilience, fisheries, and agricultural innovation.',
                'location' => 'Dumki, Patuakhali, Barishal',
                'rating' => 4.6,
                'review_count' => 180,
                'verified' => true,
                'phone' => '04427-56002',
                'website' => 'https://pstu.ac.bd',
                'facebook_url' => 'https://facebook.com/pstu.ac.bd',
                'color' => '#15803d',
                'image' => null,
                'branches' => ['Dumki Main Campus', 'Babuganj Campus'],
            ],
            [
                'slug' => 'sundarban-courier-barishal',
                'name' => 'Sundarban Courier Service (Barishal)',
                'bengali_name' => 'সুন্দরবন কুরিয়ার সার্ভিস (বরিশাল)',
                'category' => 'Courier & Digital Services',
                'description' => 'Fast parcel delivery, document courier, and freight service across all 6 southern coastal districts of Barishal.',
                'location' => 'Fazlul Haque Avenue, Barishal',
                'rating' => 4.0,
                'review_count' => 120,
                'verified' => true,
                'phone' => '0431-64580',
                'website' => 'https://sundarbancourierltd.com',
                'facebook_url' => 'https://facebook.com/sundarbancourier',
                'color' => '#ca8a04',
                'image' => null,
                'branches' => ['Barishal Sadar Branch'],
            ],

            // ==========================================
            // RANGPUR DIVISION
            // ==========================================
            [
                'slug' => 'rangpur-medical-college-hospital',
                'name' => 'Rangpur Medical College Hospital (RpMCH)',
                'bengali_name' => 'রংপুর মেডিকেল কলেজ হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => '1,000-bed government referral hospital delivering healthcare across 8 northern districts, with advanced burn, orthopedic and pediatric care.',
                'location' => 'Medical East Gate, Rangpur 5400',
                'rating' => 4.2,
                'review_count' => 280,
                'verified' => true,
                'phone' => '0521-62282',
                'website' => 'https://rpmc.gov.bd',
                'facebook_url' => 'https://facebook.com/rpmch.rangpur',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Rangpur Central Hospital'],
            ],
            [
                'slug' => 'begum-rokeya-university-rangpur',
                'name' => 'Begum Rokeya University, Rangpur (BRUR)',
                'bengali_name' => 'বেগম রোকেয়া বিশ্ববিদ্যালয়, রংপুর',
                'category' => 'Universities & Education',
                'description' => 'Fast-growing public university named after pioneering feminist Begum Rokeya, promoting higher education, science, and arts in northern Bangladesh.',
                'location' => 'Park Mor, Rangpur 5400',
                'rating' => 4.5,
                'review_count' => 210,
                'verified' => true,
                'phone' => '0521-62040',
                'website' => 'https://brur.ac.bd',
                'facebook_url' => 'https://facebook.com/brur.official',
                'color' => '#4338ca',
                'image' => null,
                'branches' => ['Park Mor Campus'],
            ],
            [
                'slug' => 'hstu-dinajpur',
                'name' => 'Hajee Mohammad Danesh Science & Technology University (HSTU)',
                'bengali_name' => 'হাজী মোহাম্মদ দানেশ বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Distinguished technical university in Dinajpur recognized for agronomy, veterinary science, computer science, and food technology.',
                'location' => 'Basherhat, Dinajpur, Rangpur',
                'rating' => 4.7,
                'review_count' => 260,
                'verified' => true,
                'phone' => '0531-61355',
                'website' => 'https://hstu.ac.bd',
                'facebook_url' => 'https://facebook.com/hstu.dinajpur.official',
                'color' => '#166534',
                'image' => null,
                'branches' => ['Dinajpur Campus'],
            ],
            [
                'slug' => 'star-tech-rangpur',
                'name' => 'Star Tech & Engineering (Rangpur)',
                'bengali_name' => 'স্টার টেক (রংপুর শাখা)',
                'category' => 'Online Electronics Shop',
                'description' => 'Regional retail outlet offering authentic IT parts, gaming setups, printers, and tech components with warranty service.',
                'location' => 'Station Road, Rangpur',
                'rating' => 4.5,
                'review_count' => 110,
                'verified' => true,
                'phone' => '09678-002003',
                'website' => 'https://startech.com.bd',
                'facebook_url' => 'https://facebook.com/star.tech.com.bd',
                'color' => '#0284c7',
                'image' => null,
                'branches' => ['Rangpur Station Road Branch'],
            ],

            // ==========================================
            // MYMENSINGH DIVISION
            // ==========================================
            [
                'slug' => 'mymensingh-medical-college-hospital',
                'name' => 'Mymensingh Medical College Hospital (MMCH)',
                'bengali_name' => 'ময়মনসিংহ মেডিকেল কলেজ হাসপাতাল',
                'category' => 'Hospitals & Clinics',
                'description' => '1,000-bed historic medical institute delivering specialized healthcare to communities across the greater Mymensingh Division.',
                'location' => 'Charpara, Mymensingh 2200',
                'rating' => 4.3,
                'review_count' => 310,
                'verified' => true,
                'phone' => '091-66063',
                'website' => 'https://mmc.gov.bd',
                'facebook_url' => 'https://facebook.com/mmch.mymensingh',
                'color' => '#0f766e',
                'image' => null,
                'branches' => ['Charpara Main Hospital'],
            ],
            [
                'slug' => 'bangladesh-agricultural-university',
                'name' => 'Bangladesh Agricultural University (BAU)',
                'bengali_name' => 'বাংলাদেশ কৃষি বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'The foremost agricultural university in Bangladesh, leading global research in crop science, veterinary medicine, and food security.',
                'location' => 'Old Brahmaputra Riverbank, Mymensingh 2202',
                'rating' => 4.9,
                'review_count' => 520,
                'verified' => true,
                'phone' => '091-67401',
                'website' => 'https://bau.edu.bd',
                'facebook_url' => 'https://facebook.com/BAU.Mymensingh.Official',
                'color' => '#15803d',
                'image' => null,
                'branches' => ['Mymensingh Sprawling 1200-acre Campus'],
            ],
            [
                'slug' => 'jkkniu-mymensingh',
                'name' => 'Jatiya Kabi Kazi Nazrul Islam University (JKKNIU)',
                'bengali_name' => 'জাতীয় কবি কাজী নজরুল ইসলাম বিশ্ববিদ্যালয়',
                'category' => 'Universities & Education',
                'description' => 'Public university in Trishal celebrating National Poet Kazi Nazrul Islam with strong programs in music, fine arts, computer science, and law.',
                'location' => 'Trishal, Mymensingh 2220',
                'rating' => 4.6,
                'review_count' => 190,
                'verified' => true,
                'phone' => '09032-56212',
                'website' => 'https://jkkniu.edu.bd',
                'facebook_url' => 'https://facebook.com/jkkniu.official',
                'color' => '#7c3aed',
                'image' => null,
                'branches' => ['Trishal Campus'],
            ],
            [
                'slug' => 'sundarban-courier-mymensingh',
                'name' => 'Sundarban Courier Service (Mymensingh)',
                'bengali_name' => 'সুন্দরবন কুরিয়ার সার্ভিস (ময়মনসিংহ)',
                'category' => 'Courier & Digital Services',
                'description' => 'Logistics parcel counter and distribution center providing prompt document and package deliveries across Mymensingh, Jamalpur, and Netrokona.',
                'location' => 'Ganginarpar, Mymensingh',
                'rating' => 4.0,
                'review_count' => 110,
                'verified' => true,
                'phone' => '091-65489',
                'website' => 'https://sundarbancourierltd.com',
                'facebook_url' => 'https://facebook.com/sundarbancourier',
                'color' => '#ca8a04',
                'image' => null,
                'branches' => ['Ganginarpar Branch'],
            ],
        ];

        foreach ($entities as $data) {
            $business = Business::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, [
                    'status' => 'approved',
                    'is_demo' => false,
                ])
            );

            // Seed an authentic verified customer review for established entities if none exists
            if ($business->reviews()->count() === 0) {
                Review::create([
                    'business_id' => $business->id,
                    'author' => 'Imtiaz Ahmed',
                    'initials' => 'IA',
                    'rating' => rand(4, 5),
                    'title' => 'Professional service and reliable staff',
                    'body' => 'Had a very smooth experience with ' . $business->name . '. The support team was responsive and all official procedures were completed accurately.',
                    'date' => now()->subDays(rand(5, 60))->toDateString(),
                    'disclaimer' => 'No conflict of interest (Verified Experience)',
                    'verified_experience' => true,
                    'location' => $business->location,
                    'facebook_url' => null,
                    'helpful_count' => rand(10, 45),
                    'discussion_count' => rand(0, 3),
                    'status' => 'published',
                ]);
            }
        }
    }
}
